server:
context-path: /micro
port: 8080
spring:
datasource:
driverClassName: com.mysql.jdbc.Driver
url: jdbc:mysql://cap-sg-prd-3.integration.ibmcloud.com:18787/inventorydb
username: dbuser
password: Pass4dbUs3R
jpa:
database: MYSQL